FROM registry.fedoraproject.org/fedora-minimal:29

LABEL maintainer="SysAlpine <mail@sysalpine.com>"

ENV BAREOS_VERSION=18.2.6 \
    BAREOS_FD_PASSWORD=changeme \
    BAREOS_FD_NAME=localhost \
    BAREOS_FD_PORT=9102 \
    BAREOS_DIR_ADDRESS=localhost \
    CONNECTION_FROM_CLIENT_TO_DIRECTOR=no \
    CONNECTION_FROM_DIRECTOR_TO_CLIENT=yes

# Add p7k bareos repo for Fedora 29
COPY bareos.repo /etc/yum.repos.d/bareos.repo

# Install Bareos Filedaemon (Client)
RUN microdnf install --nodocs bareos-client-${BAREOS_VERSION} mariadb; \
    microdnf clean all

# Install bareos configuration
COPY bareos-fd.conf /etc/bareos/bareos-fd.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 9102

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["bareos-fd", "-f", "-c", "/etc/bareos/bareos-fd.conf"]
